import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer | DocForge",
  description: "Legal disclaimers for DocForge.",
  alternates: {
    canonical: '/disclaimer',
  }
};

export default function DisclaimerPage() {
  return (
    <div className="container pt-12 pb-16 lg:pb-20 max-w-4xl">
      <h1 className="text-4xl font-bold mb-8">Disclaimer</h1>
      
      <div className="prose prose-slate dark:prose-invert max-w-none space-y-6 text-text-secondary">
        <p>Last updated: {new Date().toLocaleDateString()}</p>
        
        <section>
          <h2 className="text-2xl font-semibold text-text mb-3">General Information</h2>
          <p>The information and tools provided by DocForge ("we," "us," or "our") on docforge.com (the "Site") are for general informational and utility purposes only. All information and tools on the Site are provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or output generated by our tools.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-text mb-3">Professional Advice Disclaimer</h2>
          <p>The Site cannot and does not contain legal, financial, or professional advice. The use or reliance of any information or output generated by our tools is solely at your own risk. Always seek the advice of a qualified professional regarding any legal or critical documents.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-text mb-3">External Links Disclaimer</h2>
          <p>The Site may contain links to other websites or content belonging to or originating from third parties. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability or completeness by us.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-text mb-3">Affiliates & Advertising Disclaimer</h2>
          <p>This Site may contain links to affiliate websites, and we may receive an affiliate commission for any purchases made by you on the affiliate website using such links. We also display advertisements provided by Google AdSense and other third-party networks, which are strictly labeled as advertisements.</p>
        </section>
      </div>
    </div>
  );
}
